In [6]:
#importing to be done for numpy package
import numpy as np 
arr= np.array([10,20,30,40,50])
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [16]:
arr= np.array([1272,21,70,168,0])
print(arr)
print(type(arr))
print(arr.ndim)

[1272   21   70  168    0]
<class 'numpy.ndarray'>
1


In [15]:
arr=np.array(42)
print(arr)
# 0 dimensional array 
print(arr.ndim)

42
0


In [14]:
arr= np.array([[10,20,30,40,50],[11,21,31,41,51]])
print(arr)
print(arr.ndim)

[[10 20 30 40 50]
 [11 21 31 41 51]]
2


In [17]:
arr= np.array([[10,20,30,40,50],[11,21,31,41,51],[12,22,32,42,52]])
print(arr)
print(arr.ndim)


[[10 20 30 40 50]
 [11 21 31 41 51]
 [12 22 32 42 52]]
2


In [24]:
a=np.array(42)
b= np.array([[10,20,30,40,50],[11,21,31,41,51]])
c= np.array([[10,20,30,40,50],[11,21,31,41,51],[12,22,32,42,52]])
print(a.itemsize)
print(c[1:3:2])
print(c[::2])

4
[[11 21 31 41 51]]
[[10 20 30 40 50]
 [12 22 32 42 52]]


In [33]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr=arr.reshape(3,3)
print(arr)
print('for loop values')
for x in arr:
 print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
for loop values
[1 2 3]
[4 5 6]
[7 8 9]


In [34]:
arr=np.array([1,3,3.5])
print(type(arr))

<class 'numpy.ndarray'>


In [32]:
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [37]:
arr=np.array([[1,2,3],[11,12,13]])
arr1=np.array([[4,5,6],[14,15,16]])
arr2=np.concatenate((arr,arr1))
print(arr2)
               

[[ 1  2  3]
 [11 12 13]
 [ 4  5  6]
 [14 15 16]]


In [ ]:
arr=np.array([[1,2,3],[11,12,13]])
arr1=np.array([[4,5,6],[14,15,16]]
arr2=arr.dstack((arr,arr1))]
              print(arr2)

In [38]:
arr=np.array([1,2,3,4,5,6,7,8,9])
x=np.where(arr%2==1)
print(x)

(array([0, 2, 4, 6, 8], dtype=int64),)


In [39]:
arr=np.array([1,2,3,4,5,6,7,8,9])
x=np.where(arr%2==0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [40]:
arr=np.array([1,2,3,4,5,6,7,8,9])
filter_arr =[]
for element in arr:
    if element>4:
       filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)
        

[False, False, False, False, True, True, True, True, True]
[5 6 7 8 9]


In [41]:
arr=np.array([1,2,3,4,5,6,7,8,9])
filter_arr=arr>4
newarr=arr[filter_arr]
print(newarr)

[5 6 7 8 9]


In [77]:
from numpy import random 
x=random.randint(100)
y=random.rand()
print(x)
print(y)

71
0.6100116214749067


In [80]:
x=random.randint(100, size=(5))
z=random.randint(100, size=(3,5))
print(x)
print(z)

[28 92 24  8 14]
[[88 94 45 35 99]
 [ 7  1 52 97 99]
 [37 22 65 63 86]]


In [81]:
a=20
b=10
if b>a :
    print('b is greater than a')
elif a==b:
    print('a and b is equal')
else:
    print('smaller')
 

smaller


In [ ]:
i=1
while i>5:
    i+1
print(i)

In [ ]:
def my_fun(fruits):
    for x in fruits:
        print(x)


In [ ]:
fruits=['apple','grapes','cherry']
my_fun(fruits)